<a href="https://colab.research.google.com/github/Mr-big-cake/Fundamental_AI/blob/main/Home_Work_1(part1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.1 Импортировать NumPy под именем np

In [ ]:
import numpy as np

#1.2 Напечатать версию и конфигурацию

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#1.3 Создать вектор (одномерный массив) размера 10, заполненный нулями

In [ ]:
vector = np.full((10, ), 0)
vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#1.4 Как найти размер памяти любого массива

In [ ]:
print(vector.__sizeof__())

184


#1.5 Как получить документацию функции добавления из командной строки?

In [ ]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#1.6 Создать нулевой вектор размером 10, но пятое значение, которое равно 1

In [ ]:
vector = np.full((10,), 0)
vector[5] = 1
vector

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#1.7 Создать вектор с значениями от 10 до 49

In [ ]:
vector = np.arange(10, 49+1)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#1.8 Обратить вектор (первый элемент становится последним)

In [ ]:
vector = vector[::-1]
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#1.9 Создайте матрицу 3x3 со значениями от 0 до 8

In [ ]:
mtx = np.arange(9).reshape(3,3)
mtx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#1.10 Найти индексы ненулевых элементов от [1,2,0,0,4,0]

In [ ]:
vector = np.nonzero([1,2,0,0,4,0])
vector[0]

array([0, 1, 4])

#1.11 Создать 3x3 единичную матрицу

In [ ]:
mtx = np.full((3, 3), 1)
mtx

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#1.12 Создать массив 3x3x3 со случайными значениями

In [ ]:
arr = np.random.random((3,3,3))
arr

array([[[0.5732847 , 0.48131336, 0.25468403],
        [0.2616302 , 0.6671378 , 0.62890781],
        [0.23121803, 0.2341345 , 0.61122793]],

       [[0.41759423, 0.81964902, 0.10628356],
        [0.42538648, 0.15935865, 0.48647402],
        [0.62718968, 0.26049119, 0.31579907]],

       [[0.62888947, 0.04736868, 0.90316334],
        [0.21373097, 0.07670879, 0.93598103],
        [0.35562373, 0.20172807, 0.24582798]]])

#1.13 Создание массива 10x10 со случайными значениями и поиск минимальных и максимальных значений

In [ ]:
arr = np.random.random((10, 10))
(arr.min(), arr.max())

(0.010737232609873137, 0.9891885360119305)

#1.14 Создать случайный вектор размера 30 и найти среднее значение

In [ ]:
vector = np.random.random((30,))
vector.mean()

0.5338514456382051

#1.15 Создать двухмерный массив с 1 на границе и 0 внутри

In [ ]:
arr = np.full((3,3), 1)
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#1.16 Как добавить границу (заполненную 0's) вокруг существующего массива?

In [ ]:
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

#1.17 Каков результат следующего выражения?


In [ ]:
0 * np.nan  

nan

In [ ]:
np.nan == np.nan  

False

In [ ]:
np.inf > np.nan  

False

In [ ]:
np.nan - np.nan  

nan

In [ ]:
np.nan in set([np.nan])  

True

In [ ]:
0.3 == 3 * 0.1  

False

#1.18 Создать матрицу 5x5 со значениями 1,2,3,4 как раз под диагональю

In [ ]:
mtx = np.diag(np.arange(1, 5), k=-1)
mtx

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#1.19 Создайте матрицу 8x8 и заполните ее шахматной доской

In [ ]:
mtx = np.full((8,8), 0)
mtx[1::2,::2] = 1
mtx[::2,1::2] = 1
print(mtx)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#1.20 Рассмотрим массив размерностью (6,7,8), каков индекс (x,y,z) 100-го элемента?

In [ ]:
arr = (6,7,8)
print(np.unravel_index(100, arr))

(1, 5, 4)


#1.21 Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
arr = np.tile(np.array([[0,1,0,1],[1,0,1,0],[0,1,0,1],[1,0,1,0]]), (2,2))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#1.22 Нормализовать случайную матрицу 5x5

In [ ]:
from sklearn. preprocessing import normalize
matrix = np.random.random([5, 5])
matrix = normalize(matrix, axis= 1 , norm='l1')
matrix

array([[0.23757383, 0.31450368, 0.11822843, 0.11956823, 0.21012584],
       [0.44437642, 0.05998441, 0.19764721, 0.18299083, 0.11500113],
       [0.33904858, 0.04497883, 0.06695874, 0.25333349, 0.29568037],
       [0.17888424, 0.29976462, 0.0604354 , 0.15996546, 0.30095027],
       [0.22381002, 0.1506698 , 0.22573077, 0.11058049, 0.28920891]])

#1.23 Создать пользовательский тип dtype, который описывает цвет как четыре неподписанных байта (RGBA)

In [ ]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),("a", np.ubyte, 1)])

#1.24 Умножить матрицу 5x3 на матрицу 3x2 (реальный матричный продукт)

In [ ]:
mtx = np.dot(np.random.random((5, 3)), np.random.random((3, 2)))
mtx

array([[1.43908154, 0.54083692],
       [0.54747501, 0.35859433],
       [1.05114232, 0.50576437],
       [1.48323835, 1.01311278],
       [1.35098317, 0.91009445]])

#1.25 Если задан 1D-массив, отрицаются все элементы, находящиеся на месте между 3 и 8

In [ ]:
arr = np.random.random((10,))*10
print(arr)
arr[(arr >= 3) & (arr <= 8)] *= -1 
arr

[2.37320424 1.80891975 7.109359   5.68978758 5.73349845 1.01439704
 3.50718125 6.57608486 9.56719291 3.4150048 ]


array([ 2.37320424,  1.80891975, -7.109359  , -5.68978758, -5.73349845,
        1.01439704, -3.50718125, -6.57608486,  9.56719291, -3.4150048 ])

#1.26 Что выводит следующий скрипт?

In [ ]:
print(sum(range(5), -1)) 

9


In [ ]:
from numpy import *

In [ ]:
print(sum(range(5), -1))  # 10

10


#1.27 Где находится целочисленный вектор Z, какое из этих выражений законно?

In [ ]:
Z = np.arange(5)

In [ ]:
Z ** Z

array([  1,   1,   4,  27, 256])

In [ ]:
2 << Z >> 2 

array([0, 1, 2, 4, 8])

In [ ]:
Z < - Z 

array([False, False, False, False, False])

In [ ]:
1j * Z 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [ ]:
Z / 1 / 1

array([0., 1., 2., 3., 4.])

In [ ]:
Z < Z > Z

ValueError: ignored

#1.28 Каков результат следующих выражений?

In [ ]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#1.29 Как округлить от нуля массив поплавков ?

In [ ]:
arr = np.round(np.random.random((10,)))
arr

array([1., 1., 1., 1., 0., 1., 1., 0., 0., 1.])

#1.30 Как найти общие значения между двумя массивами?

In [ ]:
np.intersect1d(np.arange(-5, 5), np.arange(0, 10))

array([0, 1, 2, 3, 4])

#1.31 Как игнорировать все дурацкие предупреждения (не рекомендуется)?

In [ ]:
defaults = np.seterr(all="ignore")

#1.32 Is the following expressions true?

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#1.33 Как получить даты вчера, сегодня и завтра? 

In [ ]:
print(np.datetime64('today', 'D') - np.timedelta64('1'), np.datetime64('today', 'D'), np.datetime64('today', 'D') + np.timedelta64('1'))

2022-10-25 2022-10-26 2022-10-27


#2.34 Как получить все даты, соответствующие месяцу июля 2016 года?

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#2.35 Как вычислить ((А+В)*(-А/2)) на месте (без копии)?

In [ ]:
A, B, C = np.random.random((3, 3)),\
 np.random.random((3, 3)), np.random.random((3, 3))
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

array([[-3.41693784e-04, -5.79304564e-01, -4.16003455e-01],
       [-2.26185375e-01, -3.83979631e-02, -1.39669936e-01],
       [-3.01033051e-02, -7.04808941e-02, -2.69518844e-01]])

#2.36 Извлечение целочисленной части случайного массива с помощью 5 различных методов

In [110]:
arr = np.random.random((3,))*10
print(arr)
print(np.int64(arr))
print(arr.astype(np.int32))
print(np.floor(arr))
print(np.array(list(map(lambda x: int(x), list(arr)))))
print(np.round(arr))

[2.04678387 4.41334004 3.08074711]
[2 4 3]
[2 4 3]
[2. 4. 3.]
[2 4 3]
[2. 4. 3.]


#2.37 Создать матрицу 5x5 со значениями строк от 0 до 4

In [114]:
arr = np.full((5,5), np.arange(0, 5))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#2.39 Создать вектор размера 10 со значениями от 0 до 1, оба исключены

In [118]:
np.linspace(0.1 , 1, 10, endpoint=False)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])